json.logger.application.name: "prc_flightbooking"
json.logger.application.version: "1.0"
mule.env: "dev"

db:
  host: "sysflightbooking.us-e2.cloudhub.io"
  port: "80"
  protocol: "HTTP"
  basepath: "/api/"